config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_view

app_name = "core"
urlpatterns = [
    path('', room_view.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:token>", views.complete_email_verification, name="complete-verification"),
    path("login/github", views.github_login, name="github_login"),
    path("login/github/callback", views.github_callback, name="github_callback"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_callback"),
    path("login/kakao", views.kakao_login, name="kakao_login"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500">
    <div class="flex flex-col">
        <span>
            {% trans "Please don't copy us." %}
        </span>
        <span>&copy; 2019 Ayaf🔥. {% trans "All rights reserved" %}.</span>
    </div>
    {% comment %} <div class="mt-10 flex">
        {% get_current_language as LANGUAGE_CODE %}
        <select class="w-1/5 h-8" id="js-lang">
            <option value="en"
                {% if LANGUAGE_CODE == 'en' %}
                selected
                {% endif %}
            >English</option>
            <option value="es"
                {% if LANGUAGE_CODE == 'es' %}
                    selected
                {% endif %}
            >Spanish</option>
        </select>
    </div> {% endcomment %}
</footer>

templates/partials/nav.html
    <ul class="flex items-center text-sm font-medium capitalize h-full">
        <li class="nav_link">
            {% if user.is_authenticated %}
            <a href="{% url "users:logout"%}">Logout</a>
            {% else %}
        </li>
        <li class="nav_link">
            <a  href="{% url "users:login"%}" >Login</a>
        </li>
        <li class="nav_link">
              <a href="{% url "users:signup"%}">Sign up</a>
          </li> 
            {% endif %}
    </ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github_login' %}" class="btn border-2  text-gray-700 mb-2 border-gray-700">
        <i class="fab fa-github-alt mr-2 fa-lg"></i> Continue with Github
    </a>
    <a href="{% url 'users:kakao_login' %}" class="btn border text-yellow-800 mb-2 border-yellow-400 bg-yellow-400 ">
        <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>